

sentence_encoder: small
summarizer_model: small
question_answer_model: small
corpus_file: data/val.txt
max_corpus_samples: 10
doc2vec_window_size: 128 # 128 words at once
include_explanation: False
rephrase_explanation: False
num_explanation_sentence: 3
answer_score_threshold: 0.5
doc_match_score_threshold: 0.5